app = "stocktracker-besttesttest222"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  FLASK_DEBUG = "False"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 